import type { Issue, Notification } from "./civic-types";

export const DISTRICTS = [
  "Dumka",
  "Ranchi",
  "Khunti",
  "West Singhbhum",
  "Hazaribagh",
  "Sahibganj",
  "Latehar",
  "Giridih",
];

export const BLOCKS: Record<string, string[]> = {
  Dumka: ["Kathikund", "Shikaripara", "Jarmundi", "Masalia"],
  Ranchi: ["Angara", "Namkum", "Ormanjhi", "Bundu"],
  Khunti: ["Torpa", "Murhu", "Rania"],
  "West Singhbhum": ["Chaibasa", "Manoharpur", "Noamundi"],
  Hazaribagh: ["Barkagaon", "Ichak", "Katkamsandi"],
  Sahibganj: ["Borio", "Taljhari", "Mandro"],
  Latehar: ["Manika", "Balumath", "Barwadih"],
  Giridih: ["Dhanwar", "Bengabad", "Jamua"],
};

export const seedIssues = (): Issue[] => [
  {
    id: "JCC-2026-0112",
    title: "Only handpump in Bhurkunda tola has been dry for five weeks",
    category: "Water & Sanitation",
    description:
      "The single India Mark-II handpump serving 42 households runs dry after 8-10 strokes. Women walk 2.4 km to the Mayurakshi canal for drinking water. Two children were treated for diarrhoea at the Kathikund CHC in June.",
    district: "Dumka",
    block: "Kathikund",
    panchayat: "Bhurkunda",
    village: "Bhurkunda Tola",
    lat: 24.2731,
    lng: 87.2094,
    reporterName: "Sunita Devi",
    reporterKind: "citizen",
    reporterPhone: "+91 94xxxxxx41",
    anonymous: false,
    peopleAffected: 214,
    photos: ["Dry handpump head, 12 June", "Queue at canal collection point"],
    reportedAt: "2026-06-14T09:20:00Z",
    status: "solved",
    verification: {
      officer: "Rajesh Mahto, Panchayat Sevak",
      at: "2026-06-18T11:05:00Z",
      outcome: "verified",
      severity: "Critical",
      notes:
        "Site visited with Jal Sahiya. Static water level measured at 31 m against a 24 m bore depth. No alternate source within 2 km. Photographs and household count confirmed.",
    },
    ps: {
      title: "Restoring year-round drinking water at Bhurkunda Tola, Kathikund",
      context:
        "A verified single-source failure: one India Mark-II handpump at 24 m depth serves 42 households (214 people) in a hard-rock aquifer that draws down sharply after March. Nearest alternate source is 2.4 km away.",
      statement:
        "Design a low-maintenance drinking water solution for a 42-household hamlet in fractured-granite terrain where the existing 24 m borewell falls below the summer water table, using power and spares that the Panchayat can sustain without external technicians.",
      objectives: [
        "Restore at least 40 litres per person per day through the dry months (March-July).",
        "Keep recurring cost under Rs 400 per household per year.",
        "Enable repair by a trained local Jal Sahiya using district-available spares.",
        "Recharge the aquifer so the gain is not a one-season fix.",
      ],
      constraints: [
        "Grid supply averages 9 hours a day with frequent evening outages.",
        "No motorable approach for heavy rigs during monsoon.",
        "Community contribution capped at shramdaan (labour), not cash.",
      ],
      skills: [
        "Hydrogeology",
        "Solar pumping",
        "Civil / recharge structures",
        "Community operations design",
      ],
      reviewStatus: "approved",
      reviewedBy: "Dept. of Rural Development, Ranchi",
      generatedAt: "2026-06-19T06:40:00Z",
    },
    project: {
      university: "BIT Sindri, Dhanbad",
      team: "Team Jaldhara",
      members: [
        "Ankit Kumar (Civil, 3rd yr)",
        "Priya Hansda (Mech, 3rd yr)",
        "Md. Irfan (Electrical, 4th yr)",
        "Rekha Soren (Civil, 2nd yr)",
      ],
      mentor: "Dr. S. K. Verma, Dept. of Civil Engineering",
      stage: "Deployed",
      progress: 100,
      updates: [
        { at: "2026-06-24", text: "Problem statement adopted; field visit scheduled with Panchayat Sevak." },
        { at: "2026-07-02", text: "Resistivity survey done at three points; fracture zone found at 47 m near the school ground." },
        { at: "2026-07-21", text: "Design frozen: 55 m borewell + 900 Wp solar submersible + 5,000 L overhead tank, two standposts." },
        { at: "2026-08-16", text: "Recharge pit and rooftop channel completed with village shramdaan (61 person-days)." },
        { at: "2026-09-01", text: "Commissioned. Yield 3,100 L/hr at 11:00. Jal Sahiya trained on pump and controller." },
      ],
      milestones: [
        { id: "m1", title: "Hydrogeological survey report", due: "2026-07-05", done: true },
        { id: "m2", title: "Design review with Panchayat + district engineer", due: "2026-07-25", done: true, fundedBy: "Tata Steel Foundation" },
        { id: "m3", title: "Borewell drilling to fracture zone", due: "2026-08-10", done: true, fundedBy: "Tata Steel Foundation" },
        { id: "m4", title: "Solar pump + tank installation", due: "2026-08-30", done: true, fundedBy: "Usha Martin CSR" },
        { id: "m5", title: "Handover, O&M training, 30-day yield log", due: "2026-10-01", done: true },
      ],
      pledges: [
        { id: "p1", partner: "Tata Steel Foundation", kind: "Funding", detail: "Drilling and design review costs", amountInr: 420000, status: "released" },
        { id: "p2", partner: "Usha Martin CSR", kind: "Material", detail: "900 Wp solar array, controller and 5,000 L tank", amountInr: 265000, status: "released" },
        { id: "p3", partner: "Tata Steel Foundation", kind: "Mentorship", detail: "Two site engineers for commissioning week", status: "released" },
      ],
    },
    impact:
      "42 households have piped standpost water since 1 September 2026. Average collection walk fell from 2.4 km to 90 m. Monsoon recharge pit raised the post-monsoon static level by 4.1 m. Zero waterborne cases reported at Kathikund CHC from the tola in the following quarter.",
    timeline: [
      { at: "2026-06-14", actor: "Sunita Devi", role: "citizen", text: "Issue reported with 2 photos and GPS location." },
      { at: "2026-06-16", actor: "Kathikund Block", role: "panchayat", text: "Assigned to Panchayat Sevak for field verification." },
      { at: "2026-06-18", actor: "Rajesh Mahto", role: "panchayat", text: "Verified on site. Severity: Critical." },
      { at: "2026-06-19", actor: "AI assistant", role: "system", text: "Problem statement generated from verified field record." },
      { at: "2026-06-21", actor: "Dept. of Rural Development", role: "government", text: "Problem statement approved and published to universities." },
      { at: "2026-06-24", actor: "Team Jaldhara, BIT Sindri", role: "university", text: "Problem statement adopted; mentor assigned." },
      { at: "2026-07-10", actor: "Tata Steel Foundation", role: "industry", text: "Pledged Rs 4.2 lakh against drilling milestone." },
      { at: "2026-09-01", actor: "Team Jaldhara", role: "university", text: "Solution commissioned and handed over." },
      { at: "2026-09-30", actor: "Dept. of Rural Development", role: "government", text: "Impact verified and issue closed." },
    ],
  },
  {
    id: "JCC-2026-0287",
    title: "Rock-cut approach road to Torpa PHC impassable for ambulances",
    category: "Roads & Transport",
    description:
      "The 1.8 km stretch from Kudda chowk to the Torpa PHC has lost its surface. Ambulances refuse the last 600 m in monsoon; patients are carried on cots.",
    district: "Khunti",
    block: "Torpa",
    panchayat: "Kudda",
    village: "Kudda",
    lat: 22.9459,
    lng: 85.2196,
    reporterName: "Gram Vikas Sanstha",
    reporterKind: "ngo",
    reporterPhone: "+91 99xxxxxx08",
    anonymous: false,
    peopleAffected: 3800,
    photos: ["Washed-out culvert approach", "Cot transfer, 3 July"],
    reportedAt: "2026-07-03T05:45:00Z",
    status: "in_progress",
    verification: {
      officer: "Nirmala Kumari, Mukhiya",
      at: "2026-07-08T10:10:00Z",
      outcome: "verified",
      severity: "High",
      notes: "Measured 1.8 km; 4 scour points and one collapsed culvert wing wall. PHC confirms 11 refused ambulance trips in June.",
    },
    ps: {
      title: "All-weather emergency access to Torpa PHC over laterite terrain",
      context:
        "Verified loss of surface on a 1.8 km PHC approach with four scour points and a failed culvert wing wall, blocking emergency vehicles for a 3,800-person catchment.",
      statement:
        "Propose a staged, low-cost all-weather surfacing and drainage scheme for a 1.8 km rural health-access road on laterite soil with steep cross-slope, prioritising the 600 m that currently stops ambulances.",
      objectives: [
        "Guarantee ambulance access on all days of the year.",
        "Fix cross-drainage at four identified scour points.",
        "Sequence works so the critical 600 m is usable within one dry season.",
      ],
      constraints: [
        "Forest-edge alignment limits quarry material haulage.",
        "Works must pause during paddy transplanting labour peak.",
      ],
      skills: ["Pavement design", "Hydrology & drainage", "Cost estimation", "GIS survey"],
      reviewStatus: "approved",
      reviewedBy: "Dept. of Rural Development, Ranchi",
      generatedAt: "2026-07-09T04:15:00Z",
    },
    project: {
      university: "NIT Jamshedpur",
      team: "Team Pathway",
      members: ["Sohan Munda (Civil, 4th yr)", "Aarti Singh (Civil, 4th yr)", "Vikas Oraon (Civil, 3rd yr)"],
      mentor: "Prof. M. Chatterjee, Transportation Engineering",
      stage: "Prototype",
      progress: 55,
      updates: [
        { at: "2026-07-18", text: "Total-station survey and chainage-wise distress mapping completed." },
        { at: "2026-08-05", text: "Two options costed: cement-stabilised laterite base vs. WBM with cross-drains." },
        { at: "2026-08-28", text: "40 m test patch of stabilised base laid at the worst scour point for monsoon observation." },
      ],
      milestones: [
        { id: "m1", title: "Survey and distress inventory", due: "2026-07-20", done: true },
        { id: "m2", title: "Costed design options to Panchayat", due: "2026-08-10", done: true, fundedBy: "JSPL Foundation" },
        { id: "m3", title: "Test patch monsoon performance report", due: "2026-10-15", done: false },
        { id: "m4", title: "Critical 600 m execution plan", due: "2026-12-01", done: false },
      ],
      pledges: [
        { id: "p1", partner: "JSPL Foundation", kind: "Funding", detail: "Survey equipment hire and test patch material", amountInr: 180000, status: "released" },
        { id: "p2", partner: "Lafarge Holcim Bokaro", kind: "Material", detail: "18 tonnes stabilising cement for full stretch", amountInr: 310000, status: "pledged" },
      ],
    },
    timeline: [
      { at: "2026-07-03", actor: "Gram Vikas Sanstha", role: "ngo", text: "Issue reported with PHC ambulance refusal log." },
      { at: "2026-07-08", actor: "Nirmala Kumari", role: "panchayat", text: "Verified on site. Severity: High." },
      { at: "2026-07-09", actor: "AI assistant", role: "system", text: "Problem statement generated from verified field record." },
      { at: "2026-07-12", actor: "Dept. of Rural Development", role: "government", text: "Problem statement approved." },
      { at: "2026-07-15", actor: "Team Pathway, NIT Jamshedpur", role: "university", text: "Adopted problem statement." },
      { at: "2026-08-28", actor: "Team Pathway", role: "university", text: "Test patch laid; monitoring through monsoon." },
    ],
  },
  {
    id: "JCC-2026-0341",
    title: "Sahibganj riverfront ward has no waste collection; drains blocked",
    category: "Waste Management",
    description:
      "Ward 12 near the Ganga ghat has had no door-to-door collection since April. Household waste enters storm drains and floats into the river during rain.",
    district: "Sahibganj",
    block: "Borio",
    panchayat: "Ghatwari",
    village: "Ward 12, Ghat Road",
    lat: 25.2381,
    lng: 87.6416,
    reporterName: "Anonymous resident",
    reporterKind: "citizen",
    reporterPhone: "+91 87xxxxxx52",
    anonymous: true,
    peopleAffected: 1600,
    photos: ["Choked storm drain near ghat steps"],
    reportedAt: "2026-08-11T13:05:00Z",
    status: "ps_approved",
    verification: {
      officer: "Suresh Paswan, Ward Sachiv",
      at: "2026-08-15T09:30:00Z",
      outcome: "verified",
      severity: "Moderate",
      notes: "Collection vehicle off-road since April. Two drain segments fully choked. Confirmed with sanitation supervisor.",
    },
    ps: {
      title: "Decentralised waste handling for a riverfront ward at Sahibganj",
      context:
        "Verified collapse of door-to-door collection in a 1,600-person riverfront ward, with household waste entering storm drains that discharge to the Ganga.",
      statement:
        "Design a decentralised segregation and processing model for a dense riverfront ward where the municipal collection vehicle is unavailable, that intercepts waste before the storm drain network and can be run by a ward-level self-help group.",
      objectives: [
        "Intercept at least 80% of household waste at source.",
        "Create a wet-waste processing route that needs no vehicle movement.",
        "Design a drain-mouth screen that ward staff can clean daily.",
      ],
      constraints: ["No space for a ward-level transfer station wider than 3 m.", "Ghat area is under heritage/pilgrim footfall restrictions."],
      skills: ["Environmental engineering", "Solid waste systems", "Community enterprise design"],
      reviewStatus: "approved",
      reviewedBy: "Dept. of Rural Development, Ranchi",
      generatedAt: "2026-08-16T05:00:00Z",
    },
    timeline: [
      { at: "2026-08-11", actor: "Citizen (identity protected)", role: "citizen", text: "Issue reported anonymously with 1 photo." },
      { at: "2026-08-15", actor: "Suresh Paswan", role: "panchayat", text: "Verified on site. Severity: Moderate." },
      { at: "2026-08-16", actor: "AI assistant", role: "system", text: "Problem statement generated from verified field record." },
      { at: "2026-08-19", actor: "Dept. of Rural Development", role: "government", text: "Problem statement approved. Open for university adoption." },
    ],
  },
  {
    id: "JCC-2026-0402",
    title: "Upgraded middle school in Barkagaon has no functioning science lab supply",
    category: "Education",
    description:
      "Class 9-10 was added last year but the lab room has no water point, no gas and no working power socket. Practical work has not happened for two terms.",
    district: "Hazaribagh",
    block: "Barkagaon",
    panchayat: "Chepakalan",
    village: "Chepakalan",
    lat: 23.8194,
    lng: 85.2058,
    reporterName: "Meena Kumari",
    reporterKind: "citizen",
    reporterPhone: "+91 96xxxxxx77",
    anonymous: false,
    peopleAffected: 187,
    photos: ["Empty lab room", "Broken socket board"],
    reportedAt: "2026-08-29T07:15:00Z",
    status: "verified",
    verification: {
      officer: "Dinesh Ram, Panchayat Sevak",
      at: "2026-09-02T08:40:00Z",
      outcome: "verified",
      severity: "Moderate",
      notes: "Room exists, utilities absent. Headmaster confirms 187 students affected across two sections.",
    },
    timeline: [
      { at: "2026-08-29", actor: "Meena Kumari", role: "citizen", text: "Issue reported with 2 photos." },
      { at: "2026-09-02", actor: "Dinesh Ram", role: "panchayat", text: "Verified on site. Severity: Moderate. Awaiting problem statement generation." },
    ],
  },
  {
    id: "JCC-2026-0417",
    title: "Evening load-shedding stops the Manika irrigation lift for 4 hours",
    category: "Electricity",
    description:
      "The lift irrigation point on the Auranga river loses supply between 18:00 and 22:00, exactly when 60 farmers can water their rabi plots.",
    district: "Latehar",
    block: "Manika",
    panchayat: "Salaiya",
    village: "Salaiya",
    lat: 23.7431,
    lng: 84.3617,
    reporterName: "Kisan Adhikar Samiti",
    reporterKind: "ngo",
    reporterPhone: "+91 91xxxxxx23",
    anonymous: false,
    peopleAffected: 340,
    photos: ["Lift pump house with no supply"],
    reportedAt: "2026-09-04T04:30:00Z",
    status: "verifying",
    timeline: [
      { at: "2026-09-04", actor: "Kisan Adhikar Samiti", role: "ngo", text: "Issue reported with 1 photo." },
      { at: "2026-09-05", actor: "Manika Block", role: "panchayat", text: "Assigned for field verification." },
    ],
  },
  {
    id: "JCC-2026-0421",
    title: "Streetlight outage claimed on a road that has no streetlight poles",
    category: "Electricity",
    description: "Report of 14 dead streetlights on the Noamundi bypass service lane.",
    district: "West Singhbhum",
    block: "Noamundi",
    panchayat: "Balijhor",
    village: "Balijhor",
    lat: 22.1614,
    lng: 85.5064,
    reporterName: "Anonymous resident",
    reporterKind: "citizen",
    reporterPhone: "+91 70xxxxxx19",
    anonymous: true,
    peopleAffected: 0,
    photos: [],
    reportedAt: "2026-09-01T16:20:00Z",
    status: "rejected",
    verification: {
      officer: "Basanti Tudu, Panchayat Sevak",
      at: "2026-09-06T09:00:00Z",
      outcome: "rejected",
      severity: "Low",
      notes:
        "No pole line has been erected on this lane; the reported location appears to be a different road. Reporter advised to re-file with a corrected location pin.",
    },
    timeline: [
      { at: "2026-09-01", actor: "Citizen (identity protected)", role: "citizen", text: "Issue reported without photo." },
      { at: "2026-09-06", actor: "Basanti Tudu", role: "panchayat", text: "Not verified: location mismatch. Reporter may re-file." },
    ],
  },
  {
    id: "JCC-2026-0430",
    title: "Sub-centre at Bundu has no cold chain for vaccine storage",
    category: "Health",
    description:
      "The ILR unit failed in July. ANM carries vials in a thermos from the Bundu CHC, 14 km away, on immunisation days.",
    district: "Ranchi",
    block: "Bundu",
    panchayat: "Lapung",
    village: "Lapung",
    lat: 23.1611,
    lng: 85.5892,
    reporterName: "Sanjay Mahato",
    reporterKind: "citizen",
    reporterPhone: "+91 88xxxxxx31",
    anonymous: false,
    peopleAffected: 920,
    photos: ["Dead ILR unit with service tag"],
    reportedAt: "2026-09-06T11:00:00Z",
    status: "reported",
    timeline: [
      { at: "2026-09-06", actor: "Sanjay Mahato", role: "citizen", text: "Issue reported with 1 photo. Awaiting Panchayat assignment." },
    ],
  },
];

export const seedNotifications = (): Notification[] => [
  {
    id: "n1",
    to: ["panchayat"],
    text: "New report JCC-2026-0430 in Lapung awaits field verification.",
    at: "2026-09-06T11:02:00Z",
    issueId: "JCC-2026-0430",
    read: false,
  },
  {
    id: "n2",
    to: ["government"],
    text: "JCC-2026-0402 is verified and ready for AI problem statement generation.",
    at: "2026-09-02T08:45:00Z",
    issueId: "JCC-2026-0402",
    read: false,
  },
  {
    id: "n3",
    to: ["university"],
    text: "Approved problem statement open for adoption: Sahibganj riverfront waste (JCC-2026-0341).",
    at: "2026-08-19T06:00:00Z",
    issueId: "JCC-2026-0341",
    read: false,
  },
  {
    id: "n4",
    to: ["industry"],
    text: "Team Pathway needs 18 t stabilising cement for milestone 3 (JCC-2026-0287).",
    at: "2026-08-29T09:30:00Z",
    issueId: "JCC-2026-0287",
    read: false,
  },
  {
    id: "n5",
    to: ["citizen", "ngo"],
    text: "Your reported issue JCC-2026-0112 was closed with verified impact.",
    at: "2026-09-30T10:00:00Z",
    issueId: "JCC-2026-0112",
    read: true,
  },
];
